### ISSUE TITLE
How to enable ImageMagick SVG support?

### ISSUE THREAD

**Issue by maikol-solis** [mpsq/emacs-gcc-wayland-devel-builder#23]
Hi! 

I want to say first thanks for this package. It's a lifesaver to use emacs 28 without the pain to compile every time the whole thing. 

Today I installed this other package that I want to test 

https://github.com/alphapapa/org-graph-view

But I got this error

```
org-graph-view: This Emacs does not appear to be built with ImageMagick SVG support 
```

How do I could enable the ImageMagick support for this? 

Best

**Comment by mpsq** [comment]
Hi Maikol,

Thanks for the kind words! Since Emacs 27, ImageMagick is disabled by default. Support can still be enabled (via a compilation flag) but I would prefer not to since I am trying to be as close as possible to a vanilla binary of Emacs. Technically, Emacs is able to support SVGs natively now and does not need ImageMagick to function. I seems that it was disabled because it was the source of big security holes. The way to fix this would be for the lib to be updated to use the native API. There is a ticket for that: https://github.com/alphapapa/org-graph-view/issues/6.

Thanks again

**Comment by maikol-solis** [comment]
Thanks @mpsq. I'll review it thoroughly. Best.
