### ISSUE TITLE
Release 28.2.50 changelog reflect incorrect upstream branch

### ISSUE THREAD

**Issue by mangkoran** [mpsq/emacs-gcc-wayland-devel-builder#30]
First of all, thank you for your hard work maintaining this package. It is truly time-saving for us who want to quickly use pgtk and JIT Emacs.

It seems that the upstream this repo use to build Emacs is yet to update to 28.2. The [latest commit](https://github.com/flatwhatson/emacs/commit/3ddccb531ded81fd81e76494d043323d5785db8f) on flatwhatson's was on May 17. If we see the the Emacs upstream at Savannah, 28.2 is [released](https://git.savannah.gnu.org/cgit/emacs.git/tag/?h=emacs-28.2) on 2022-09-12.

![Screenshot_20221012-063045_Chrome](https://user-images.githubusercontent.com/57625126/195217454-8137debb-0a6f-49f1-aa2c-c4e85faff824.png)

Apologize for not testing the package first, but is the [new release](https://github.com/mpsq/emacs-gcc-wayland-devel-builder/releases/tag/28.2.50.151998) actually updated to 28.2?

**Comment by mangkoran** [comment]
Additionally, the AUR's pkgver is yet to be updated too.

![image](https://user-images.githubusercontent.com/57625126/195220825-ecd67117-b137-4924-a8be-772a5cdf13b9.png)

**Comment by mpsq** [comment]
The changelog is auto-generated using GitHub's api. The reason why it is truncated is because it is too big (so it is actually paged). I don't have time to like into this tbh, I want to prioritize the release first. PRs are welcome though, the relevant script can be tweaked to handle paging properly https://github.com/mpsq/emacs-gcc-wayland-devel-builder/blob/main/scripts/build-artifacts.bash#L35

**Comment by mangkoran** [comment]
I will check the code first and try to help whenever I can.

Then, I will close this issue. Thank you for your response!
